version: "3.8"

services:
  ngrok:
    image: wernight/ngrok
    command: ["ngrok", "http", "hubspot-app:8080"]
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - app-network

  hubspot-app:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: hubspot-integration
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - ngrok
    env_file:
      - .env
    command: >
      sh -c "./wait-for-ngrok.sh &&
            export $$(cat /app/ngrok.env | xargs) &&
            java -jar hubspot-api-integration.jar"

networks:
  app-network:
    driver: bridge