spring:
  application:
    name: hubspot-api-integration
  
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: ${HUBSPOT_CLIENT_ID}
            client-secret: ${HUBSPOT_CLIENT_SECRET}
            redirect-uri: ${HUBSPOT_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: crm.objects.contacts.read,crm.objects.contacts.write

        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token

hubspot:
  crm:
    api-contact:
      base-url-create: https://api.hubapi.com/crm/v3/objects/contacts