spring:
  application:
    name: hubspot-api-integration
  
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: ${HUBSPOT_CLIENT_ID}
            client-secret: ${HUBSPOT_CLIENT_SECRET}
            redirect-uri: ${HUBSPOT_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: crm.objects.contacts.read,crm.objects.contacts.write

        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token

hubspot:
  crm:
    api-contact:
      base-url-create: https://api.hubapi.com/crm/v3/objects/contacts